apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-bootstrap-application
  namespace: argocd  # <-- replace this with the actual namespace (e.g., argocd)
  labels:
    name: argocd-bootstrap-application
spec:
  project: default
  source:
    repoURL: https://github.com/PX-Perform-IN3838/modern-cloud-devops-stack.git  # <-- replace with your Git repo URL from where ArgoCD should synch
    targetRevision: "HEAD"  
    path: gitops/environments/dev
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
