# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-app
  labels:
    app: url-shortener
spec:
  replicas: 1 # You can adjust this based on environment (e.g., 1 for dev, 3 for prod)
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      serviceAccountName: sa-url-shortener  # Link to the Service Account with IRSA role
      #nodeSelector:
      #  workload-type: karpenter-exclusive
      #tolerations:
      #  - key: "workload.k8s.io/karpenter-exclusive-app"
      #    operator: "Exists" # Matches any value for this key
      #    effect: "NoSchedule" 
      containers:
      - name: url-shortener
        image: "" # IMPORTANT: Replace with your ECR image URL
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m" 
          limits:
            memory: "128Mi"
            cpu: "200m" 
