# k8s/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: url-shortener-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: url-shortener-app # Must match the name of your Deployment
  minReplicas: 1 # Minimum number of pods to maintain, even under low load
  maxReplicas: 10 # Maximum number of pods to scale up to
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Target 50% average CPU utilization