---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-app
spec:
  template:
    spec:
      containers:
      - name: url-shortener
        image: <image name>:production # configure the ECR image endpoint
